### ISSUE TITLE
Worker is an Invalid Worker

### ISSUE THREAD

**Issue by mbaeuerle** [sheharyarn/que#1]
I have an issue with the worker. I can start the application just once and it runs (in iex).
But when I want to rerun it (by starting a new iex session), I get the `Worker is an Invalid Worker` error. 
I can only fix that by renaming the Worker. Then it works again once before I have to rename it again.

I am using Elixir 1.4.2 and Que 0.3.1

**Comment by sheharyarn** [comment]
Hi @mbaeuerle. Can you post the code for the worker, the code you're calling and the stack trace?

**Comment by mbaeuerle** [comment]
I created a minimal project where I could reproduce the problem. The worker looks like this:
``` elixir
defmodule Worker do
  use Que.Worker

  def perform(work) do
   IO.puts work 
  end
end
```

And adding to `Que` like this:
``` elixir
  def hello do
    Que.add(Worker, "test")
  end
```

Now running it the first time is no problem. The second time the error occurs:
<img width="943" alt="grafik" src="https://cloud.githubusercontent.com/assets/1345394/25694666/de3cb3cc-30af-11e7-9d64-0b03cb83f8c5.png">

I think this has something to do with compiling the file. Everytime it is compiled (ie. when changing the code) something else is done which is not done when just rerunning it.

**Comment by sheharyarn** [comment]
This is indeed a serious bug @mbaeuerle, thank you for reporting it. It seems like an issue with how the Erlang VM lazy loads some modules. In my tests, this happens randomly. I'm working on a fix right now.

Thank you again.

**Comment by sheharyarn** [comment]
I've released a new version with the patch. You should not have this problem any more. Thank you.

**Comment by mbaeuerle** [comment]
Thanks for fixing so fast!
